/** Static VN stock → sector mapping. Covers major HOSE/HNX stocks. Unknown → "Khác". */
export const SECTOR_MAP: Record<string, string> = {
  // Ngân hàng (Banking)
  VCB: "Ngân hàng",
  BID: "Ngân hàng",
  CTG: "Ngân hàng",
  TCB: "Ngân hàng",
  MBB: "Ngân hàng",
  VPB: "Ngân hàng",
  ACB: "Ngân hàng",
  STB: "Ngân hàng",
  HDB: "Ngân hàng",
  LPB: "Ngân hàng",
  MSB: "Ngân hàng",
  SHB: "Ngân hàng",
  VIB: "Ngân hàng",
  NAB: "Ngân hàng",
  TPB: "Ngân hàng",
  OCB: "Ngân hàng",
  BAB: "Ngân hàng",
  BVB: "Ngân hàng",
  KLB: "Ngân hàng",

  // Bất động sản (Real Estate)
  VIC: "Bất động sản",
  VHM: "Bất động sản",
  NVL: "Bất động sản",
  PDR: "Bất động sản",
  DXG: "Bất động sản",
  KDH: "Bất động sản",
  NLG: "Bất động sản",
  DIG: "Bất động sản",
  CEO: "Bất động sản",
  HDG: "Bất động sản",
  CII: "Xây dựng",
  LDG: "Bất động sản",
  SCR: "Bất động sản",
  VRE: "Bất động sản",
  AGG: "Bất động sản",
  ITC: "Bất động sản",
  SJS: "Bất động sản",
  DPM: "Năng lượng",
  DXS: "Bất động sản",
  TDC: "Bất động sản",
  BCG: "Bất động sản",
  NBB: "Bất động sản",
  TN1: "Bất động sản",
  CRE: "Bất động sản",

  // Vật liệu (Materials / Steel)
  HPG: "Vật liệu",
  HSG: "Vật liệu",
  NKG: "Vật liệu",
  VGC: "Vật liệu",
  VCS: "Vật liệu",
  SMC: "Vật liệu",
  TIS: "Vật liệu",
  TVN: "Vật liệu",
  HT1: "Vật liệu",
  BCC: "Vật liệu",
  BMP: "Vật liệu",
  AAA: "Vật liệu",

  // Hàng tiêu dùng (Consumer Goods)
  MSN: "Tiêu dùng",
  SAB: "Tiêu dùng",
  VNM: "Tiêu dùng",
  MCH: "Tiêu dùng",
  KDC: "Tiêu dùng",
  ANV: "Tiêu dùng",
  SBT: "Tiêu dùng",
  LSS: "Tiêu dùng",
  CLC: "Tiêu dùng",
  QNS: "Tiêu dùng",
  HAG: "Nông nghiệp",
  VHC: "Tiêu dùng",
  IDI: "Tiêu dùng",
  HNG: "Nông nghiệp",
  BAF: "Tiêu dùng",
  MML: "Tiêu dùng",

  // Bán lẻ (Retail)
  MWG: "Bán lẻ",
  FRT: "Bán lẻ",
  PNJ: "Bán lẻ",
  DGW: "Bán lẻ",
  APG: "Bán lẻ",

  // Công nghệ (Technology)
  FPT: "Công nghệ",
  CMG: "Công nghệ",
  ELC: "Công nghệ",
  SAM: "Công nghệ",
  VGI: "Công nghệ",
  ITD: "Công nghệ",

  // Năng lượng (Energy)
  GAS: "Năng lượng",
  PLX: "Năng lượng",
  OIL: "Năng lượng",
  PVT: "Năng lượng",
  PVD: "Năng lượng",
  PVS: "Năng lượng",
  BSR: "Năng lượng",
  PCG: "Năng lượng",
  PGS: "Năng lượng",
  GEG: "Năng lượng",
  REE: "Năng lượng",
  SBA: "Năng lượng",
  PPC: "Năng lượng",
  NT2: "Năng lượng",
  CHP: "Năng lượng",

  // Chứng khoán (Securities)
  SSI: "Chứng khoán",
  VND: "Chứng khoán",
  HCM: "Chứng khoán",
  MBS: "Chứng khoán",
  CTS: "Chứng khoán",
  VCI: "Chứng khoán",
  BSI: "Chứng khoán",
  AGR: "Chứng khoán",
  TVS: "Chứng khoán",
  FTS: "Chứng khoán",
  SHS: "Chứng khoán",
  EVS: "Chứng khoán",
  TCI: "Chứng khoán",
  VIX: "Chứng khoán",
  APS: "Chứng khoán",

  // Bảo hiểm (Insurance)
  BVH: "Bảo hiểm",
  PVI: "Bảo hiểm",
  BMI: "Bảo hiểm",
  PTI: "Bảo hiểm",
  MIG: "Bảo hiểm",

  // Công nghiệp / Vận tải (Industrial / Transport)
  VJC: "Công nghiệp",
  ACV: "Công nghiệp",
  GMD: "Công nghiệp",
  HAH: "Công nghiệp",
  PAN: "Công nghiệp",
  VIP: "Công nghiệp",
  TMS: "Công nghiệp",
  STG: "Công nghiệp",
  TCO: "Công nghiệp",
  VSC: "Công nghiệp",
  GVR: "Công nghiệp",

  // Nông nghiệp (Agriculture)
  GEX: "Nông nghiệp",

  // Xây dựng (Construction)
  CTD: "Xây dựng",
  HBC: "Xây dựng",
  LCG: "Xây dựng",
  RLC: "Xây dựng",
  VCG: "Xây dựng",
  FCN: "Xây dựng",
  C47: "Xây dựng",
};

export const ALL_TRACKED_SYMBOLS = Object.keys(SECTOR_MAP);

/** VN30 components for liquidity chart (intraday cumulative volume). */
export const VN30_SYMBOLS = [
  "VCB",
  "BID",
  "CTG",
  "TCB",
  "MBB",
  "VPB",
  "ACB",
  "STB",
  "VIC",
  "VHM",
  "NVL",
  "VRE",
  "HPG",
  "MSN",
  "SAB",
  "VNM",
  "GAS",
  "PLX",
  "FPT",
  "MWG",
  "PNJ",
  "SSI",
  "HCM",
  "VJC",
  "ACV",
  "GVR",
  "BVH",
  "PDR",
  "KDH",
];

export function getSector(symbol: string): string {
  return SECTOR_MAP[symbol] ?? "Khác";
}
